#!/usr/bin/env python
#
# this script will upload an arduino compiled sketch
# to a WiFi connected device
#
#
from __future__ import print_function
import os
import sys 
import glob
import stat
import time
import subprocess
#
#===========================================================
#------ do not change anything above this line! ------------
#
#------ where pyton is located -----------------------------
# You can find this by entering the following commands in a 
# terminal/command window:
# 1  > python
# 2  >>> import sys
# 3  >>> sys.executable
# 4  '/usr/local/bin/python'
# 5  >>> quit()
#
# copy/paste the string from line 4 between os.path.join()
#
PYTHON = os.path.join('/usr/local/bin/python')
## print(">   PYTHON [" + PYTHON + "]")
#
#------ this is the Sketch Location (see preferences.txt) --
BUILDPATH = os.path.join("/Users/(YourLoginName)/Documenten/arduinoBuild")
## print('>BUILDPATH [' + BUILDPATH + ']')
#
#------ Edit this ESPOTAPY to point to the location --------
#------ where your espota.py file is located        --------
ESPOTAPY  = os.path.join("/Users/(YourLoginName)/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.0/tools/espota.py")
## print('> ESPOTAPY [' + ESPOTAPY + ']')
#
#------ do not change anything below this line! ------------
#===========================================================
 15 #===========================================================
 16 #------ do not change anything above this line! ------------
 17 #
 18 #------ where pyton is located -----------------------------
 19 # You can find this by entering the following commands in a
 20 # terminal/command window:
 21 # 1  > python
 22 # 2  >>> import sys
 23 # 3  >>> sys.executable
 24 # 4  '/usr/local/bin/python'
 25 # 5  >>> quit()
 26 #
 27 # copy/paste the string from line 4 between os.path.join()
 28 #
 29 PYTHON = os.path.join('/usr/local/bin/python')
 30 ## print(">   PYTHON [" + PYTHON + "]")
 31 #
 32 #------ this is the Sketch Location (see preferences.txt) --
 33 BUILDPATH = os.path.join("/Users/(YourLoginName)/Documenten/arduinoBuild")
 34 ## print('>BUILDPATH [' + BUILDPATH + ']')
 35 #
 36 #------ Edit this ESPOTAPY to point to the location --------
 37 #------ where your espota.py file is located        --------
 38 ESPOTAPY  = os.path.join("/Users/(YourLoginName)/Library/Arduino15/packages/esp8266/    hardware/esp8266/2.5.0/tools/espota.py")
 39 ## print('> ESPOTAPY [' + ESPOTAPY + ']')
 40 #
 41 #------ do not change anything below this line! ------------
 42 #===========================================================
#
##print(sys.argv)
MODNAME   = os.path.basename(sys.argv[0])
#
#------ yes/no question ------------------------------------
def yes_or_no(question):
    try:
        #print("try: raw_input()")
        reply = str(raw_input(MODNAME+' : '+question+' (y/N)? ')).lower().strip()
    except:
        #print("except: input()")
        reply = str(input(MODNAME+' : '+question+' (y/N)? ')).lower().strip()
    #
    if reply[:1] == 'y':
        return True
    return False
#
#
#------ check number of arguments on command line ----------
arguments = sys.argv[1:]
count = len(arguments)
if (count != 1):
   print("Error: use", MODNAME, "<IPaddress device>")
   sys.exit(1)
#
#------ first argument must be IP address of the device ----
IPADDRESS = sys.argv[1]
#
# where are we?
CWD = os.getcwd()
##print(MODNAME,": Started in [", CWD, "]")
#
#------ does build-path exists -----------------------------
if ( not os.path.exists(BUILDPATH)):
   print(MODNAME,": ["+BUILDPATH+"]")
   print(MODNAME,": Build path does not exist")
   sys.exit(2)
if (not os.path.isdir(BUILDPATH)):
   print(MODNAME,": ["+ BUILDPATH+ "] is not a directory")
   sys.exit(2)
#
#
#------ change directory to BUILDPATH ----------------------
os.chdir(BUILDPATH)
print(MODNAME,": Changed to [", os.getcwd(), "]")
#
#------ now check if there is only 1 bin file --------------
noBins = 0
for binFile in glob.glob('*.*.bin'):
    noBins += 1
    print(MODNAME,": [", noBins, "] [", binFile, "]")
#
if (noBins > 1):
    print(MODNAME,": There are more than one (1) *.*.bin files!")
    print(MODNAME,": Abort")
    sys.exit(3)
#
if (noBins < 1):
    print(MODNAME,": There are no *.*.bin files!")
    print(MODNAME,": Abort")
    sys.exit(3)
#
#------ ok, all went well .. -------------------------------
print(MODNAME,": bin File Found ", binFile)
#
fileStatsObj = os.stat ( binFile )
modificationTime = time.ctime ( fileStatsObj [ stat.ST_MTIME ] )
print(MODNAME,": Last Modified  ", modificationTime)
#
if (not yes_or_no('Continue')):
    sys.exit(4)
#
#------ build the espota command line and execute ----------
ESPOTA = PYTHON + ' "' + ESPOTAPY + '" -i ' + IPADDRESS + ' -p 8266 --auth= -f ' + binFile
print(MODNAME+': ['+ ESPOTA+ ']')
#
print('----------------------------------------------------------------------------')
print(MODNAME,': espota -i ', IPADDRESS,' -f ', binFile)
ouput = subprocess.call( ESPOTA, shell=True )
#
# go back to CWD
os.chdir(CWD)
##print(MODNAME,": .. and we'r back at [", os.getcwd(), "]")
print("Done!")
